using System;
using System.Collections.Generic;
using MvvmHelpers;
using SQLite.Net.Attributes;
using WTSqLExt.Attributes;

namespace DataObjects.DAOS
{
    [Table("WoodlandConditionSubSection")]
    public class WoodlandConditionSubSection : ObservableObject
    {
        [PrimaryKey, AutoIncrement]
        public int ID { get; set; }
        public int FeatureMonitoringID { get; set; }
        public bool WholeSite { get; set; }
        public int? KeyFeatureID { get; set; }
        public int? StratumID { get; set; }
        public string StratumDescription { get; set; }
        public bool? OverallInterventionDesirable { get; set; }
        public bool? OverallInterventionAchievable { get; set; }
        public string OverallConclusionsAndRecommendations { get; set; }
        public int? TotalTreeCanopyCoverPercentCurrent { get; set; }
        public int? TotalTreeCanopyCoverPercentMin { get; set; }
        public int? TotalTreeCanopyCoverPercentMax { get; set; }
        public int? OpenSpaceSemiNaturalHabitatPercentCurrent { get; set; }
        public int? OpenSpaceSemiNaturalHabitatPercentMin { get; set; }
        public int? OpenSpaceSemiNaturalHabitatPercentMax { get; set; }
        public int? OpenSpaceRidesPercentCurrent { get; set; }
        public int? OpenSpaceRidesPercentMin { get; set; }
        public int? OpenSpaceRidesPercentMax { get; set; }
        public int? OpenSpaceTemporaryPercentCurrent { get; set; }
        public int? OpenSpaceTemporaryPercentMin { get; set; }
        public int? OpenSpaceTemporaryPercentMax { get; set; }
        public int? OpenSpaceWaterFeaturesPercentCurrent { get; set; }
        public int? OpenSpaceWaterFeaturesPercentMin { get; set; }
        public int? OpenSpaceWaterFeaturesPercentMax { get; set; }
        public int? ShrubCoverPercentCurrent { get; set; }
        public int? ShrubCoverPercentMin { get; set; }
        public int? ShrubCoverPercentMax { get; set; }
        public bool? InterventionDesirable { get; set; }
        public bool? InterventionAchievable { get; set; }
        public string NotesAction { get; set; }
        public int? TAVeteranPollardsAncientCoppiceStoolsID { get; set; }
        public int? TAVeteranPollardsAncientCoppiceStoolsPlot1ID { get; set; }
        public int? TAVeteranPollardsAncientCoppiceStoolsPlot2ID { get; set; }
        public int? TAVeteranPollardsAncientCoppiceStoolsPlot3ID { get; set; }
        public int? TAVeteranPollardsAncientCoppiceStoolsPlot4ID { get; set; }
        public int? TAVeteranPollardsAncientCoppiceStoolsPlot5ID { get; set; }
        public int? TA100_200YearsID { get; set; }
        public int? TA100_200YearsPlot1ID { get; set; }
        public int? TA100_200YearsPlot2ID { get; set; }
        public int? TA100_200YearsPlot3ID { get; set; }
        public int? TA100_200YearsPlot4ID { get; set; }
        public int? TA100_200YearsPlot5ID { get; set; }
        public int? TA50_100YearsID { get; set; }
        public int? TA50_100YearsPlot1ID { get; set; }
        public int? TA50_100YearsPlot2ID { get; set; }
        public int? TA50_100YearsPlot3ID { get; set; }
        public int? TA50_100YearsPlot4ID { get; set; }
        public int? TA50_100YearsPlot5ID { get; set; }
        public int? TA20_50YearsID { get; set; }
        public int? TA20_50YearsPlot1ID { get; set; }
        public int? TA20_50YearsPlot2ID { get; set; }
        public int? TA20_50YearsPlot3ID { get; set; }
        public int? TA20_50YearsPlot4ID { get; set; }
        public int? TA20_50YearsPlot5ID { get; set; }
        public int? TA20YearsID { get; set; }
        public int? TA20YearsPlot1ID { get; set; }
        public int? TA20YearsPlot2ID { get; set; }
        public int? TA20YearsPlot3ID { get; set; }
        public int? TA20YearsPlot4ID { get; set; }
        public int? TA20YearsPlot5ID { get; set; }
        public bool TAInterventionDesirable { get; set; }
        public bool TAInterventionAchievable { get; set; }
        public string TANotesActions { get; set; }
        public int? TSNativesNumberPresent { get; set; }
        public int? TSNativesNumberPresentPlot1 { get; set; }
        public int? TSNativesNumberPresentPlot2 { get; set; }
        public int? TSNativesNumberPresentPlot3 { get; set; }
        public int? TSNativesNumberPresentPlot4 { get; set; }
        public int? TSNativesNumberPresentPlot5 { get; set; }
        public int? TSNonNativesNumberPresent { get; set; }
        public int? TSNonNativesNumberPresentPlot1 { get; set; }
        public int? TSNonNativesNumberPresentPlot2 { get; set; }
        public int? TSNonNativesNumberPresentPlot3 { get; set; }
        public int? TSNonNativesNumberPresentPlot4 { get; set; }
        public int? TSNonNativesNumberPresentPlot5 { get; set; }
        public bool TSCanopyDominatedByOneOrTwoSPP { get; set; }
        public bool TSCanopyDominatedByOneOrTwoSPPPlot1 { get; set; }
        public bool TSCanopyDominatedByOneOrTwoSPPPlot2 { get; set; }
        public bool TSCanopyDominatedByOneOrTwoSPPPlot3 { get; set; }
        public bool TSCanopyDominatedByOneOrTwoSPPPlot4 { get; set; }
        public bool TSCanopyDominatedByOneOrTwoSPPPlot5 { get; set; }
        public bool TSInterventionDesirable { get; set; }
        public bool TSInterventionAchievable { get; set; }
        public string TSNotesActions { get; set; }
        public int? SSNativesNumberPresent { get; set; }
        public int? SSNativesNumberPresentPlot1 { get; set; }
        public int? SSNativesNumberPresentPlot2 { get; set; }
        public int? SSNativesNumberPresentPlot3 { get; set; }
        public int? SSNativesNumberPresentPlot4 { get; set; }
        public int? SSNativesNumberPresentPlot5 { get; set; }
        public int? SSNonNativesNumberPresent { get; set; }
        public int? SSNonNativesNumberPresentPlot1 { get; set; }
        public int? SSNonNativesNumberPresentPlot2 { get; set; }
        public int? SSNonNativesNumberPresentPlot3 { get; set; }
        public int? SSNonNativesNumberPresentPlot4 { get; set; }
        public int? SSNonNativesNumberPresentPlot5 { get; set; }
        public bool SSShrubLayerDominatedByOneOrTwoSPP { get; set; }
        public bool SSShrubLayerDominatedByOneOrTwoSPPPlot1 { get; set; }
        public bool SSShrubLayerDominatedByOneOrTwoSPPPlot2 { get; set; }
        public bool SSShrubLayerDominatedByOneOrTwoSPPPlot3 { get; set; }
        public bool SSShrubLayerDominatedByOneOrTwoSPPPlot4 { get; set; }
        public bool SSShrubLayerDominatedByOneOrTwoSPPPlot5 { get; set; }
        public int? SSDAFOROfCoverID { get; set; }
        public int? SSDAFOROfCoverPlot1ID { get; set; }
        public int? SSDAFOROfCoverPlot2ID { get; set; }
        public int? SSDAFOROfCoverPlot3ID { get; set; }
        public int? SSDAFOROfCoverPlot4ID { get; set; }
        public int? SSDAFOROfCoverPlot5ID { get; set; }
        public bool SSInterventionDesirable { get; set; }
        public bool SSInterventionAchievable { get; set; }
        public string SSNotesActions { get; set; }
        public int? LTRSeedlingsLess10cmID { get; set; }
        public int? LTRSeedlingsLess10cmPlot1ID { get; set; }
        public int? LTRSeedlingsLess10cmPlot2ID { get; set; }
        public int? LTRSeedlingsLess10cmPlot3ID { get; set; }
        public int? LTRSeedlingsLess10cmPlot4ID { get; set; }
        public int? LTRSeedlingsLess10cmPlot5ID { get; set; }
        public int? LTRSeedlings10_100cmID { get; set; }
        public int? LTRSeedlings10_100cmPlot1ID { get; set; }
        public int? LTRSeedlings10_100cmPlot2ID { get; set; }
        public int? LTRSeedlings10_100cmPlot3ID { get; set; }
        public int? LTRSeedlings10_100cmPlot4ID { get; set; }
        public int? LTRSeedlings10_100cmPlot5ID { get; set; }
        public int? LTRSaplingsGreater100cmID { get; set; }
        public int? LTRSaplingsGreater100cmPlot1ID { get; set; }
        public int? LTRSaplingsGreater100cmPlot2ID { get; set; }
        public int? LTRSaplingsGreater100cmPlot3ID { get; set; }
        public int? LTRSaplingsGreater100cmPlot4ID { get; set; }
        public int? LTRSaplingsGreater100cmPlot5ID { get; set; }
        public int? LTRCoppiceRegrowthOrSuckeringID { get; set; }
        public int? LTRCoppiceRegrowthOrSuckeringPlot1ID { get; set; }
        public int? LTRCoppiceRegrowthOrSuckeringPlot2ID { get; set; }
        public int? LTRCoppiceRegrowthOrSuckeringPlot3ID { get; set; }
        public int? LTRCoppiceRegrowthOrSuckeringPlot4ID { get; set; }
        public int? LTRCoppiceRegrowthOrSuckeringPlot5ID { get; set; }
        public bool LTRInterventionDesirable { get; set; }
        public bool LTRInterventionAchievable { get; set; }
        public string LTRNotesActions { get; set; }
        public int? LSRSeedlingsLess10cmID { get; set; }
        public int? LSRSeedlingsLess10cmPlot1ID { get; set; }
        public int? LSRSeedlingsLess10cmPlot2ID { get; set; }
        public int? LSRSeedlingsLess10cmPlot3ID { get; set; }
        public int? LSRSeedlingsLess10cmPlot4ID { get; set; }
        public int? LSRSeedlingsLess10cmPlot5ID { get; set; }
        public int? LSRSeedlings10_100cmID { get; set; }
        public int? LSRSeedlings10_100cmPlot1ID { get; set; }
        public int? LSRSeedlings10_100cmPlot2ID { get; set; }
        public int? LSRSeedlings10_100cmPlot3ID { get; set; }
        public int? LSRSeedlings10_100cmPlot4ID { get; set; }
        public int? LSRSeedlings10_100cmPlot5ID { get; set; }
        public int? LSRSaplingsGreater100cmID { get; set; }
        public int? LSRSaplingsGreater100cmPlot1ID { get; set; }
        public int? LSRSaplingsGreater100cmPlot2ID { get; set; }
        public int? LSRSaplingsGreater100cmPlot3ID { get; set; }
        public int? LSRSaplingsGreater100cmPlot4ID { get; set; }
        public int? LSRSaplingsGreater100cmPlot5ID { get; set; }
        public int? LSRCoppiceRegrowthOrSuckeringID { get; set; }
        public int? LSRCoppiceRegrowthOrSuckeringPlot1ID { get; set; }
        public int? LSRCoppiceRegrowthOrSuckeringPlot2ID { get; set; }
        public int? LSRCoppiceRegrowthOrSuckeringPlot3ID { get; set; }
        public int? LSRCoppiceRegrowthOrSuckeringPlot4ID { get; set; }
        public int? LSRCoppiceRegrowthOrSuckeringPlot5ID { get; set; }
        public bool LSRInterventionDesirable { get; set; }
        public bool LSRInterventionAchievable { get; set; }
        public string LSRNotesActions { get; set; }
        public int? RTSNativesNumberPresent { get; set; }
        public int? RTSNativesNumberPresentPlot1 { get; set; }
        public int? RTSNativesNumberPresentPlot2 { get; set; }
        public int? RTSNativesNumberPresentPlot3 { get; set; }
        public int? RTSNativesNumberPresentPlot4 { get; set; }
        public int? RTSNativesNumberPresentPlot5 { get; set; }
        public int? RTSNonNativesNumberPresent { get; set; }
        public int? RTSNonNativesNumberPresentPlot1 { get; set; }
        public int? RTSNonNativesNumberPresentPlot2 { get; set; }
        public int? RTSNonNativesNumberPresentPlot3 { get; set; }
        public int? RTSNonNativesNumberPresentPlot4 { get; set; }
        public int? RTSNonNativesNumberPresentPlot5 { get; set; }
        public bool RTSDominatedByOneOrTwoSPP { get; set; }
        public bool RTSDominatedByOneOrTwoSPPPlot1 { get; set; }
        public bool RTSDominatedByOneOrTwoSPPPlot2 { get; set; }
        public bool RTSDominatedByOneOrTwoSPPPlot3 { get; set; }
        public bool RTSDominatedByOneOrTwoSPPPlot4 { get; set; }
        public bool RTSDominatedByOneOrTwoSPPPlot5 { get; set; }
        public bool RTSInterventionDesirable { get; set; }
        public bool RTSInterventionAchievable { get; set; }
        public string RTSNotesActions { get; set; }
        public int? RSSNativesNumberPresent { get; set; }
        public int? RSSNativesNumberPresentPlot1 { get; set; }
        public int? RSSNativesNumberPresentPlot2 { get; set; }
        public int? RSSNativesNumberPresentPlot3 { get; set; }
        public int? RSSNativesNumberPresentPlot4 { get; set; }
        public int? RSSNativesNumberPresentPlot5 { get; set; }
        public int? RSSNonNativesNumberPresent { get; set; }
        public int? RSSNonNativesNumberPresentPlot1 { get; set; }
        public int? RSSNonNativesNumberPresentPlot2 { get; set; }
        public int? RSSNonNativesNumberPresentPlot3 { get; set; }
        public int? RSSNonNativesNumberPresentPlot4 { get; set; }
        public int? RSSNonNativesNumberPresentPlot5 { get; set; }
        public bool RSSDominatedByOneOrTwoSPP { get; set; }
        public bool RSSDominatedByOneOrTwoSPPPlot1 { get; set; }
        public bool RSSDominatedByOneOrTwoSPPPlot2 { get; set; }
        public bool RSSDominatedByOneOrTwoSPPPlot3 { get; set; }
        public bool RSSDominatedByOneOrTwoSPPPlot4 { get; set; }
        public bool RSSDominatedByOneOrTwoSPPPlot5 { get; set; }
        public bool RSSInterventionDesirable { get; set; }
        public bool RSSInterventionAchievable { get; set; }
        public string RSSNotesActions { get; set; }
        public int? FAncientWoodlandPlantsSpecialistsID { get; set; }
        public int? FAncientWoodlandPlantsSpecialistsPlot1ID { get; set; }
        public int? FAncientWoodlandPlantsSpecialistsPlot2ID { get; set; }
        public int? FAncientWoodlandPlantsSpecialistsPlot3ID { get; set; }
        public int? FAncientWoodlandPlantsSpecialistsPlot4ID { get; set; }
        public int? FAncientWoodlandPlantsSpecialistsPlot5ID { get; set; }
        public int? FOtherWoodlandPlantsGeneralistsID { get; set; }
        public int? FOtherWoodlandPlantsGeneralistsPlot1ID { get; set; }
        public int? FOtherWoodlandPlantsGeneralistsPlot2ID { get; set; }
        public int? FOtherWoodlandPlantsGeneralistsPlot3ID { get; set; }
        public int? FOtherWoodlandPlantsGeneralistsPlot4ID { get; set; }
        public int? FOtherWoodlandPlantsGeneralistsPlot5ID { get; set; }
        public int? FOtherNativePlantsID { get; set; }
        public int? FOtherNativePlantsPlot1ID { get; set; }
        public int? FOtherNativePlantsPlot2ID { get; set; }
        public int? FOtherNativePlantsPlot3ID { get; set; }
        public int? FOtherNativePlantsPlot4ID { get; set; }
        public int? FOtherNativePlantsPlot5ID { get; set; }
        public int? FCoarseVegetationID { get; set; }
        public int? FCoarseVegetationPlot1ID { get; set; }
        public int? FCoarseVegetationPlot2ID { get; set; }
        public int? FCoarseVegetationPlot3ID { get; set; }
        public int? FCoarseVegetationPlot4ID { get; set; }
        public int? FCoarseVegetationPlot5ID { get; set; }
        public int? FOtherPlantsID { get; set; }
        public int? FOtherPlantsPlot1ID { get; set; }
        public int? FOtherPlantsPlot2ID { get; set; }
        public int? FOtherPlantsPlot3ID { get; set; }
        public int? FOtherPlantsPlot4ID { get; set; }
        public int? FOtherPlantsPlot5ID { get; set; }
        public int? FNoVegetationID { get; set; }
        public int? FNoVegetationPlot1ID { get; set; }
        public int? FNoVegetationPlot2ID { get; set; }
        public int? FNoVegetationPlot3ID { get; set; }
        public int? FNoVegetationPlot4ID { get; set; }
        public int? FNoVegetationPlot5ID { get; set; }
        public bool FInterventionDesirable { get; set; }
        public bool FInterventionAchievable { get; set; }
        public string FNotesActions { get; set; }
        public int? DStandingID { get; set; }
        public int? DStandingPlot1ID { get; set; }
        public int? DStandingPlot2ID { get; set; }
        public int? DStandingPlot3ID { get; set; }
        public int? DStandingPlot4ID { get; set; }
        public int? DStandingPlot5ID { get; set; }
        public int? DFallenID { get; set; }
        public int? DFallenPlot1ID { get; set; }
        public int? DFallenPlot2ID { get; set; }
        public int? DFallenPlot3ID { get; set; }
        public int? DFallenPlot4ID { get; set; }
        public int? DFallenPlot5ID { get; set; }
        public bool DInterventionDesirable { get; set; }
        public bool DInterventionAchievable { get; set; }
        public string DNotesActions { get; set; }
        public int? ADSquirrelsID { get; set; }
        public int? ADSquirrelsPlot1ID { get; set; }
        public int? ADSquirrelsPlot2ID { get; set; }
        public int? ADSquirrelsPlot3ID { get; set; }
        public int? ADSquirrelsPlot4ID { get; set; }
        public int? ADSquirrelsPlot5ID { get; set; }
        public int? ADDeerID { get; set; }
        public int? ADDeerPlot1ID { get; set; }
        public int? ADDeerPlot2ID { get; set; }
        public int? ADDeerPlot3ID { get; set; }
        public int? ADDeerPlot4ID { get; set; }
        public int? ADDeerPlot5ID { get; set; }
        public int? ADRabBITsID { get; set; }
        public int? ADRabBITsPlot1ID { get; set; }
        public int? ADRabBITsPlot2ID { get; set; }
        public int? ADRabBITsPlot3ID { get; set; }
        public int? ADRabBITsPlot4ID { get; set; }
        public int? ADRabBITsPlot5ID { get; set; }
        public int? ADOtherID { get; set; }
        public int? ADOtherPlot1ID { get; set; }
        public int? ADOtherPlot2ID { get; set; }
        public int? ADOtherPlot3ID { get; set; }
        public int? ADOtherPlot4ID { get; set; }
        public int? ADOtherPlot5ID { get; set; }
        public bool ADInterventionDesirable { get; set; }
        public bool ADInterventionAchievable { get; set; }
        public string ADNotesActions { get; set; }
        public int? IRhododendronID { get; set; }
        public int? IRhododendronPlot1ID { get; set; }
        public int? IRhododendronPlot2ID { get; set; }
        public int? IRhododendronPlot3ID { get; set; }
        public int? IRhododendronPlot4ID { get; set; }
        public int? IRhododendronPlot5ID { get; set; }
        public int? IHimalayanBalsamID { get; set; }
        public int? IHimalayanBalsamPlot1ID { get; set; }
        public int? IHimalayanBalsamPlot2ID { get; set; }
        public int? IHimalayanBalsamPlot3ID { get; set; }
        public int? IHimalayanBalsamPlot4ID { get; set; }
        public int? IHimalayanBalsamPlot5ID { get; set; }
        public int? IJapaneseKnotweedID { get; set; }
        public int? IJapaneseKnotweedPlot1ID { get; set; }
        public int? IJapaneseKnotweedPlot2ID { get; set; }
        public int? IJapaneseKnotweedPlot3ID { get; set; }
        public int? IJapaneseKnotweedPlot4ID { get; set; }
        public int? IJapaneseKnotweedPlot5ID { get; set; }
        public int? IOtherID { get; set; }
        public int? IOtherPlot1ID { get; set; }
        public int? IOtherPlot2ID { get; set; }
        public int? IOtherPlot3ID { get; set; }
        public int? IOtherPlot4ID { get; set; }
        public int? IOtherPlot5ID { get; set; }
        public bool IInterventionDesirable { get; set; }
        public bool IInterventionAchievable { get; set; }
        public string INotesActions { get; set; }
        public int? THNotifiablePestOrDiseaseID { get; set; }
        public int? THNotifiablePestOrDiseasePlot1ID { get; set; }
        public int? THNotifiablePestOrDiseasePlot2ID { get; set; }
        public int? THNotifiablePestOrDiseasePlot3ID { get; set; }
        public int? THNotifiablePestOrDiseasePlot4ID { get; set; }
        public int? THNotifiablePestOrDiseasePlot5ID { get; set; }
        public int? THOtherDiseaseOrPestID { get; set; }
        public int? THOtherDiseaseOrPestPlot1ID { get; set; }
        public int? THOtherDiseaseOrPestPlot2ID { get; set; }
        public int? THOtherDiseaseOrPestPlot3ID { get; set; }
        public int? THOtherDiseaseOrPestPlot4ID { get; set; }
        public int? THOtherDiseaseOrPestPlot5ID { get; set; }
        public bool THInterventionDesirable { get; set; }
        public bool THInterventionAchievable { get; set; }
        public string THNotesActions { get; set; }
        public int? HIOneOffImpactsID { get; set; }
        public int? HIOneOffImpactsPlot1ID { get; set; }
        public int? HIOneOffImpactsPlot2ID { get; set; }
        public int? HIOneOffImpactsPlot3ID { get; set; }
        public int? HIOneOffImpactsPlot4ID { get; set; }
        public int? HIOneOffImpactsPlot5ID { get; set; }
        public int? HIContinuousImpactsID { get; set; }
        public int? HIContinuousImpactsPlot1ID { get; set; }
        public int? HIContinuousImpactsPlot2ID { get; set; }
        public int? HIContinuousImpactsPlot3ID { get; set; }
        public int? HIContinuousImpactsPlot4ID { get; set; }
        public int? HIContinuousImpactsPlot5ID { get; set; }
        public bool HIInterventionDesirable { get; set; }
        public bool HIInterventionAchievable { get; set; }
        public string HINotesActions { get; set; }
        public bool Deleted { get; set; }
        public bool IsProtected { get; set; }
        public bool IsHistorical { get; set; }
        public bool IsDefaultValue { get; set; }
        public System.DateTime LMDT { get; set; }
        public int LMUID { get; set; }
        public DateTime? CRDT { get; set; }
        public int? CRUID { get; set; }
        public DateTime? DLDT { get; set; }
        public int? DLUID { get; set; }
        
    }
}
